#!/usr/bin/env bash
# Compile the HPLT toy corpus and upload it to LUMI-O.
# Run from the project root on LUMI-C.
#
# Prerequisites:
#   - Python 3 available (for to_vert.py)
#   - singularity available on PATH (/usr/bin/singularity on LUMI; no module load needed)
#   - rclone configured via: module load lumio && lumio-conf
#     This generates ~/.config/rclone/rclone.conf with the remote named
#     "lumi-<PROJECT_ID>-private" (e.g. lumi-462001491-private).
#   - LUMI-O bucket "turkunlp-noske-corpora" already created at auth.lumidata.eu
#
# Note: HPLT_INPUT derives from $DATA (set by ~/lumi-env.sh); no edit needed on
# project migration. Scratch is not persistent across renewals (see platform.md).
#
# Usage:
#   ./scripts/compile_and_upload.sh [LIMIT]
#   LIMIT: number of documents to convert (default: 1000; 0 = all)
#
# Outputs:
#   vert/hplt_toy.vert      — manatee vertical file
#   compiled/hplt_toy/      — compiled manatee corpus
#   (uploaded to lumi-462001491-private:turkunlp-noske-corpora/hplt_toy/)

set -euo pipefail
source ~/lumi-env.sh   # provides $DATA and $LUMI_PROJECT (see platform.md)

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIMIT="${1:-1000}"

# Path derives from $DATA (set by ~/lumi-env.sh); no edit needed on project migration
HPLT_INPUT="$DATA/hplt-samples/v3/fin_Latn_sample_100000.jsonl"
VERT_FILE="$PROJECT_ROOT/vert/hplt_toy.vert"
REGISTRY_DIR="$PROJECT_ROOT/registry"
COMPILED_DIR="$PROJECT_ROOT/compiled"
SIF="$PROJECT_ROOT/noske-okd.sif"
# Remote name as generated by lumio-conf; derived from the active project ($LUMI_PROJECT)
BUCKET="lumi-${LUMI_PROJECT#project_}-private:turkunlp-noske-corpora"

# ── Step 1: Generate vertical ────────────────────────────────────────────────
echo "=== Step 1: Generate vertical (limit=$LIMIT) ==="
mkdir -p "$PROJECT_ROOT/vert"
python3 "$PROJECT_ROOT/scripts/to_vert.py" \
    --input "$HPLT_INPUT" \
    --output "$VERT_FILE" \
    --limit "$LIMIT"
echo "Vertical written to $VERT_FILE"

# ── Step 2: Pull Apptainer SIF (cached after first run) ─────────────────────
echo "=== Step 2: Apptainer image ==="
if [ ! -f "$SIF" ]; then
    echo "Pulling noske-okd image (first run; this may take a few minutes)..."
    singularity pull "$SIF" docker://ghcr.io/tuomaslundberg/noske-okd:latest
else
    echo "Using cached SIF: $SIF"
fi

# ── Step 3: Compile with compilecorp via Apptainer ──────────────────────────
# Bind-mount:
#   registry/ → /var/lib/manatee/registry  (so compilecorp finds the registry file)
#   compiled/  → /var/lib/manatee/data     (so compilecorp writes there directly)
#   vert/      → /work/vert                (vertical file path for compilecorp arg)
echo "=== Step 3: Compile corpus ==="
mkdir -p "$COMPILED_DIR"
singularity exec \
    --bind "$REGISTRY_DIR:/var/lib/manatee/registry" \
    --bind "$COMPILED_DIR:/var/lib/manatee/data" \
    --bind "$PROJECT_ROOT/vert:/work/vert" \
    "$SIF" \
    compilecorp --no-ske hplt_toy /work/vert/hplt_toy.vert
echo "Compiled corpus at: $COMPILED_DIR/hplt_toy/"

# ── Step 4: Upload to LUMI-O ─────────────────────────────────────────────────
echo "=== Step 4: Upload to LUMI-O ==="
rclone copy "$COMPILED_DIR/hplt_toy/" "$BUCKET/hplt_toy/" --progress
echo "Upload complete: $BUCKET/hplt_toy/"
echo ""
echo "All done. Apply manifests/00-secret.yaml, 02-configmap.yaml, and"
echo "03-deployment.yaml to OKD, then restart the deployment."
